sudo: required
services:
  - docker

before_install:
  - docker build -t aleksandrborkov/docker-react -f Dockerfile.dev .

script:
  - docker run aleksandrborkov/docker-react npm run test -- --coverage
