sudo: required
services:
  - docker

before_install:
  - docker build -t aleksandrborkov/docker-react -f Dockerfile.dev .

script:
  # Workaround for "npm test -- --coverage" never exits (!) - add key "-e CI=true"
  # See https://stackoverflow.com/questions/55991641/npm-test-coverage-never-exits
  - docker run -e CI=true aleksandrborkov/docker-react yarn test -- --coverage
